; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = bs_esp

[common]
lib_deps =
    https://github.com/thingSoC/Embedis
    https://github.com/sui77/rc-switch.git
;     https://github.com/marvinroger/async-mqtt-client.git
    https://github.com/thingSoC/embedis.git
    https://github.com/knolleary/pubsubclient.git
    https://github.com/adafruit/Adafruit_NeoPixel.git
    ArduinoJson
    LittleFs
    https://github.com/xoseperez/eeprom_rotate.git
    https://github.com/kiot-innovations/justwifi.git#ef4f222
    https://github.com/kiot-innovations/async-mqtt-client#2392687
    https://github.com/kiot-innovations/ESPAsyncTCP
    https://github.com/kiot-innovations/ESPAsyncWebServer
    https://github.com/kiot-innovations/debounceevent.git#8b567f0 
    https://github.com/kiot-innovations/mDNSResolver
    https://github.com/kiot-innovations/Cryptosuite.git#e845dfe
    https://github.com/kiot-innovations/AES.git#2f24726
    https://github.com/kiot-innovations/fauxmoesp.git
    Hash
    https://github.com/ayushsharma82/ElegantOTA.git#79c562e

shared_libdeps_dir= libraries/

[env]
lib_extra_dirs =
    ${common.shared_libdeps_dir}

[env:bct_3phase]
platform = espressif8266
board_build.partitions = huge_app
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 512000
build_flags = -DBCT_3PHASE=1
lib_deps =
        ${common.lib_deps}


[env:bkct_3phase]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DBKCT_3PHASE=1
lib_deps =
        ${common.lib_deps}


[env:yct_3phase]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 512000
board_build.partitions = huge_app
build_flags = -DYCT_3PHASE=1
lib_deps =
        ${common.lib_deps}


[env:energy_meter_1]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DENERGY_METER_1=1
lib_deps =
        ${common.lib_deps}

[env:tunable_light]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DTUNABLE_LIGHT=1
lib_deps =
        ${common.lib_deps}

[env:rgbw_light]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DRGBW_LIGHT=1
lib_deps =
        ${common.lib_deps}


;-----------------------------------------

[env:touch_panel_4]
platform = espressif8266
board = nodemcuv2
board_build.partitions = huge_app
framework = arduino
monitor_speed = 115200
upload_speed = 512000
build_flags = -DTOUCH_PANEL_4=1
lib_deps =
        ${common.lib_deps}

[env:touch_panel_2]
platform = espressif8266
board = nodemcuv2
board_build.partitions = huge_app
framework = arduino
monitor_speed = 115200
upload_speed = 512000
build_flags = -DTOUCH_PANEL_2=1
lib_deps =
        ${common.lib_deps}

[env:touch_panel_4p1]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app
upload_speed = 512000
build_flags = -DTOUCH_PANEL_4P1=1
lib_deps =
        ${common.lib_deps}



[env:touch_panel_10]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DTOUCH_PANEL_10=1
lib_deps =
        ${common.lib_deps}
;-----------------------------------------
[env:modular_touch_1]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DMODULAR_TOUCH_1=1
lib_deps =
        ${common.lib_deps}
;-----------------------------------------
[env:modular_touch_4]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DMODULAR_TOUCH_4=1
lib_deps =
        ${common.lib_deps}
;-----------------------------------------
[env:modular_touch_fan]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DMODULAR_TOUCH_FAN=1
lib_deps =
        ${common.lib_deps}
;-----------------------------------------
[env:modular_touch_2]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DMODULAR_TOUCH_2=1
lib_deps =
        ${common.lib_deps}
;-----------------------------------------
[env:node_switch_1]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DNODE_SWITCH_1=1
lib_deps =
        ${common.lib_deps}

[env:node_switch_1p1]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DNODE_SWITCH_1P1=1
lib_deps =
        ${common.lib_deps}

[env:node_switch_2]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DNODE_SWITCH_2=1
lib_deps =
        ${common.lib_deps}
        
[env:node_switch_2p1]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DNODE_SWITCH_2P1=1
lib_deps =
        ${common.lib_deps}

[env:node_switch_4p1]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DNODE_SWITCH_4P1=1
lib_deps =
        ${common.lib_deps}


[env:node_switch_4]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.partitions = huge_app
monitor_speed = 115200
upload_speed = 512000
build_flags = -DNODE_SWITCH_4=1
lib_deps =
        ${common.lib_deps}
;-----------------------------------------
;-----------------------------------------

;  The  src_dir  is set to  bs_esp  which is the directory where the source code is located. The  lib_deps  is set to the  embedis  library. 
;  The  platform  is set to  espressif8266  and the  board  is set to  nodemcuv2 . The  framework  is set to  arduino . The  monitor_speed  and  upload_speed  are set to  115200 . The  build_flags  is set to  -DDEBUG_ESP_PORT=Serial . 
;  The  lib_deps  is set to  ${common.lib_deps}  which is the  embedis  library. 
;  The  platformio.ini  file is used to configure the PlatformIO project. 
;  The  bs_esp  directory contains the source code for the project. 
;  The  bs_esp  directory contains the following files: 
;  bs_esp.ino 
;  #include <Arduino.h>
